include_guard(GLOBAL)

function(uvpp_protocols_configure_http_backends target)
  if(NOT UVPP_PROTOCOLS_HTTP1_BACKEND MATCHES "^(auto|llhttp|stub)$")
    message(FATAL_ERROR "UVPP_PROTOCOLS_HTTP1_BACKEND must be auto, llhttp, or stub")
  endif()

  if(NOT UVPP_PROTOCOLS_HTTP2_BACKEND MATCHES "^(auto|nghttp2|none)$")
    message(FATAL_ERROR "UVPP_PROTOCOLS_HTTP2_BACKEND must be auto, nghttp2, or none")
  endif()

  set(http1_backend_found FALSE)
  if(NOT UVPP_PROTOCOLS_HTTP1_BACKEND STREQUAL "stub")
    find_package(llhttp CONFIG QUIET)
    if(TARGET llhttp::llhttp)
      target_link_libraries(${target} PRIVATE llhttp::llhttp)
      set(http1_backend_found TRUE)
    elseif(TARGET llhttp)
      target_link_libraries(${target} PRIVATE llhttp)
      set(http1_backend_found TRUE)
    else()
      find_package(PkgConfig QUIET)
      if(PkgConfig_FOUND)
        pkg_check_modules(LLHTTP QUIET IMPORTED_TARGET llhttp)
        if(TARGET PkgConfig::LLHTTP)
          target_link_libraries(${target} PRIVATE PkgConfig::LLHTTP)
          set(http1_backend_found TRUE)
        endif()
      endif()
    endif()

    if(http1_backend_found)
      target_compile_definitions(${target} PRIVATE UVPP_PROTOCOLS_DETAIL_HAS_LLHTTP=1)
      message(STATUS "uvpp-protocols: HTTP/1 backend: llhttp")
    elseif(UVPP_PROTOCOLS_HTTP1_BACKEND STREQUAL "llhttp")
      message(FATAL_ERROR "llhttp was requested but was not found")
    else()
      target_compile_definitions(${target} PRIVATE UVPP_PROTOCOLS_DETAIL_HAS_LLHTTP=0)
      message(STATUS "uvpp-protocols: HTTP/1 backend: stub")
    endif()
  else()
    target_compile_definitions(${target} PRIVATE UVPP_PROTOCOLS_DETAIL_HAS_LLHTTP=0)
    message(STATUS "uvpp-protocols: HTTP/1 backend: stub")
  endif()

  set(http2_backend_found FALSE)
  if(NOT UVPP_PROTOCOLS_HTTP2_BACKEND STREQUAL "none")
    find_package(nghttp2 CONFIG QUIET)
    if(TARGET nghttp2::nghttp2)
      target_link_libraries(${target} PRIVATE nghttp2::nghttp2)
      set(http2_backend_found TRUE)
    else()
      find_package(PkgConfig QUIET)
      if(PkgConfig_FOUND)
        pkg_check_modules(NGHTTP2 QUIET IMPORTED_TARGET libnghttp2)
        if(TARGET PkgConfig::NGHTTP2)
          target_link_libraries(${target} PRIVATE PkgConfig::NGHTTP2)
          set(http2_backend_found TRUE)
        endif()
      endif()
    endif()

    if(http2_backend_found)
      target_compile_definitions(${target} PRIVATE UVPP_PROTOCOLS_DETAIL_HAS_NGHTTP2=1)
      message(STATUS "uvpp-protocols: HTTP/2 backend reserved: libnghttp2")
    elseif(UVPP_PROTOCOLS_HTTP2_BACKEND STREQUAL "nghttp2")
      message(FATAL_ERROR "libnghttp2 was requested but was not found")
    else()
      target_compile_definitions(${target} PRIVATE UVPP_PROTOCOLS_DETAIL_HAS_NGHTTP2=0)
      message(STATUS "uvpp-protocols: HTTP/2 backend reserved: none")
    endif()
  else()
    target_compile_definitions(${target} PRIVATE UVPP_PROTOCOLS_DETAIL_HAS_NGHTTP2=0)
    message(STATUS "uvpp-protocols: HTTP/2 backend reserved: none")
  endif()
endfunction()

